#include "omdata.h"
#include "i18n.h"

extern oter_t oterlist[num_ter_types];
oter_t oterlist[num_ter_types] = {
{"nothing",   '%',  c_white,  0, no_extras, false, false},
{N_("crater"),    'O',  c_red,    2, field_extras, false, false},
{N_("field"),   '.',  c_brown,  2, field_extras, false, false},
{N_("dirt lot"),    'O',  c_brown,  1, field_extras, false, false},
{N_("forest"),    'F',  c_green,  3, field_extras, false, false},
{N_("forest"),    'F',  c_green,  4, field_extras, false, false},
{N_("swamp"),   'F',  c_cyan,   4, field_extras, false, false},
{N_("bee hive"),    '8',  c_yellow, 3, field_extras, false, false},
{N_("forest"),    'F',  c_green,  3, field_extras, false, false},
/* The tile above is a spider pit. */
{N_("fungal bloom"),  'T',  c_ltgray, 2, field_extras, false, false},
{N_("highway"),   'H',  c_dkgray, 2, road_extras, false, false},
{N_("highway"),   '=',  c_dkgray, 2, road_extras, false, false},
{"BUG",     '%',  c_magenta,  0, no_extras, false, false},
{N_("road"),          LINE_XOXO,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_OXOX,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_XXOO,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_OXXO,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_OOXX,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_XOOX,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_XXXO,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_XXOX,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_XOXX,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_OXXX,  c_dkgray, 2, road_extras, false, false},
{N_("road"),          LINE_XXXX,  c_dkgray, 2, road_extras, false, false},
{N_("road, manhole"), LINE_XXXX,  c_yellow, 2, road_extras, true, false},
{N_("bridge"),    '|',  c_dkgray, 2, road_extras, false, false},
{N_("bridge"),    '-',  c_dkgray, 2, road_extras, false, false},
{N_("river"),   'R',  c_blue,   1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("river bank"),    'R',  c_ltblue, 1, no_extras, false, false},
{N_("house"),   '^',  c_ltgreen,  5, build_extras, false, false},
{N_("house"),   '>',  c_ltgreen,  5, build_extras, false, false},
{N_("house"),   'v',  c_ltgreen,  5, build_extras, false, false},
{N_("house"),   '<',  c_ltgreen,  5, build_extras, false, false},
{N_("house"),   '^',  c_ltgreen,  5, build_extras, false, false},
{N_("house"),   '>',  c_ltgreen,  5, build_extras, false, false},
{N_("house"),   'v',  c_ltgreen,  5, build_extras, false, false},
{N_("house"),   '<',  c_ltgreen,  5, build_extras, false, false},
{N_("parking lot"),   'O',  c_dkgray, 1, build_extras, false, false},
{N_("park"),    'O',  c_green,  2, build_extras, false, false},
{N_("gas station"),   '^',  c_ltblue, 5, build_extras, false, false},
{N_("gas station"),   '>',  c_ltblue, 5, build_extras, false, false},
{N_("gas station"),   'v',  c_ltblue, 5, build_extras, false, false},
{N_("gas station"),   '<',  c_ltblue, 5, build_extras, false, false},
{N_("pharmacy"),    '^',  c_ltred,  5, build_extras, false, false},
{N_("pharmacy"),    '>',  c_ltred,  5, build_extras, false, false},
{N_("pharmacy"),    'v',  c_ltred,  5, build_extras, false, false},
{N_("pharmacy"),    '<',  c_ltred,  5, build_extras, false, false},
{N_("grocery store"), '^',  c_green,  5, build_extras, false, false},
{N_("grocery store"), '>',  c_green,  5, build_extras, false, false},
{N_("grocery store"), 'v',  c_green,  5, build_extras, false, false},
{N_("grocery store"), '<',  c_green,  5, build_extras, false, false},
{N_("hardware store"),  '^',  c_cyan,   5, build_extras, false, false},
{N_("hardware store"),  '>',  c_cyan,   5, build_extras, false, false},
{N_("hardware store"),  'v',  c_cyan,   5, build_extras, false, false},
{N_("hardware store"),  '<',  c_cyan,   5, build_extras, false, false},
{N_("electronics store"),   '^',  c_yellow, 5, build_extras, false, false},
{N_("electronics store"),   '>',  c_yellow, 5, build_extras, false, false},
{N_("electronics store"),   'v',  c_yellow, 5, build_extras, false, false},
{N_("electronics store"),   '<',  c_yellow, 5, build_extras, false, false},
{N_("sporting goods store"),'^',  c_ltcyan, 5, build_extras, false, false},
{N_("sporting goods store"),'>',  c_ltcyan, 5, build_extras, false, false},
{N_("sporting goods store"),'v',  c_ltcyan, 5, build_extras, false, false},
{N_("sporting goods store"),'<',  c_ltcyan, 5, build_extras, false, false},
{N_("liquor store"),  '^',  c_magenta,  5, build_extras, false, false},
{N_("liquor store"),  '>',  c_magenta,  5, build_extras, false, false},
{N_("liquor store"),  'v',  c_magenta,  5, build_extras, false, false},
{N_("liquor store"),  '<',  c_magenta,  5, build_extras, false, false},
{N_("gun store"),   '^',  c_red,    5, build_extras, false, false},
{N_("gun store"),   '>',  c_red,    5, build_extras, false, false},
{N_("gun store"),   'v',  c_red,    5, build_extras, false, false},
{N_("gun store"),   '<',  c_red,    5, build_extras, false, false},
{N_("clothing store"),  '^',  c_blue,   5, build_extras, false, false},
{N_("clothing store"),  '>',  c_blue,   5, build_extras, false, false},
{N_("clothing store"),  'v',  c_blue,   5, build_extras, false, false},
{N_("clothing store"),  '<',  c_blue,   5, build_extras, false, false},
{N_("library"),   '^',  c_brown,  5, build_extras, false, false},
{N_("library"),   '>',  c_brown,  5, build_extras, false, false},
{N_("library"),   'v',  c_brown,  5, build_extras, false, false},
{N_("library"),   '<',  c_brown,  5, build_extras, false, false},
{N_("restaurant"),    '^',  c_pink,   5, build_extras, false, false},
{N_("restaurant"),    '>',  c_pink,   5, build_extras, false, false},
{N_("restaurant"),    'v',  c_pink,   5, build_extras, false, false},
{N_("restaurant"),    '<',  c_pink,   5, build_extras, false, false},
{N_("subway station"),  'S',  c_yellow, 5, build_extras, true, false},
{N_("subway station"),  'S',  c_yellow, 5, build_extras, true, false},
{N_("subway station"),  'S',  c_yellow, 5, build_extras, true, false},
{N_("subway station"),  'S',  c_yellow, 5, build_extras, true, false},
{N_("garage"),              'O',    c_white,       5, build_extras, false, false},
{N_("garage"),              'O',    c_white,       5, build_extras, false, false},
{N_("garage"),              'O',    c_white,       5, build_extras, false, false},
{N_("garage"),              'O',    c_white,       5, build_extras, false, false},
{N_("cabin"),              'C',    i_green,       5, build_extras, false, false},
{N_("farm"),              '^',    i_brown,       5, build_extras, false, false},
{N_("farm field"),              '#',    i_brown,       5, field_extras, false, false},
{N_("police station"),  '^',  h_yellow, 5, build_extras, false, false},
{N_("police station"),  '>',  h_yellow, 5, build_extras, false, false},
{N_("police station"),  'v',  h_yellow, 5, build_extras, false, false},
{N_("police station"),  '<',  h_yellow, 5, build_extras, false, false},
{N_("bank"),    '$',  c_ltgray, 5, no_extras, false, false},
{N_("bank"),    '$',  c_ltgray, 5, no_extras, false, false},
{N_("bank"),    '$',  c_ltgray, 5, no_extras, false, false},
{N_("bank"),    '$',  c_ltgray, 5, no_extras, false, false},
{N_("bar"),     '^',  i_magenta,    5, build_extras, false, false},
{N_("bar"),     '>',  i_magenta,    5, build_extras, false, false},
{N_("bar"),     'v',  i_magenta,    5, build_extras, false, false},
{N_("bar"),     '<',  i_magenta,    5, build_extras, false, false},
{N_("pawn shop"),   '^',  c_white,  5, build_extras, false, false},
{N_("pawn shop"),   '>',  c_white,  5, build_extras, false, false},
{N_("pawn shop"),   'v',  c_white,  5, build_extras, false, false},
{N_("pawn shop"),   '<',  c_white,  5, build_extras, false, false},
{N_("mil. surplus"),  '^',  i_ltgray, 5, build_extras, false, false},
{N_("mil. surplus"),  '>',  i_ltgray, 5, build_extras, false, false},
{N_("mil. surplus"),  'v',  i_ltgray, 5, build_extras, false, false},
{N_("mil. surplus"),  '<',  i_ltgray, 5, build_extras, false, false},
{N_("megastore"),   '+',  c_ltblue, 5, build_extras, false, false},
{N_("megastore"),   'M',  c_blue,   5, build_extras, false, false},
{N_("hospital"),    'H',  c_ltred,  5, build_extras, false, false},
{N_("hospital"),    'H',  c_red,    5, build_extras, false, false},
{N_("mansion"),   'M',  c_ltgreen,  5, build_extras, false, false},
{N_("mansion"),   'M',  c_green,  5, build_extras, false, false},
{N_("fema camp"),   '+',  c_blue, 5, build_extras, false, false},
{N_("fema camp"),   'F',  i_blue, 5, build_extras, false, false},
{N_("evac shelter"),  '+',  c_white,  2, no_extras, true, false},
{N_("evac shelter"),  '+',  c_white,  2, no_extras, false, true},
{N_("LMOE shelter"),  '+',  c_red,  2, no_extras, true, false},
{N_("LMOE shelter"),  '+',  c_red,  2, no_extras, false, true},
{N_("science lab"),   'L',  c_ltblue, 5, no_extras, false, false},
{N_("science lab"),   'L',  c_blue,   5, no_extras, true, false},
{N_("science lab"),   'L',  c_ltblue, 5, no_extras, false, false},
{N_("science lab"),   'L',  c_cyan,   5, no_extras, false, false},
{N_("nuclear plant"), 'P',  c_ltgreen,  5, no_extras, false, false},
{N_("nuclear plant"), 'P',  c_ltgreen,  5, no_extras, false, false},
{N_("military bunker"), 'B',  c_dkgray, 2, no_extras, true, true},
{N_("military outpost"),  'M',  c_dkgray, 2, build_extras, false, false},
{N_("missile silo"),  '0',  c_ltgray, 2, no_extras, false, false},
{N_("missile silo"),  '0',  c_ltgray, 2, no_extras, false, false},
{N_("strange temple"),  'T',  c_magenta,  5, no_extras, true, false},
{N_("strange temple"),  'T',  c_pink,   5, no_extras, true, false},
{N_("strange temple"),  'T',  c_pink,   5, no_extras, false, false},
{N_("strange temple"),  'T',  c_yellow, 5, no_extras, false, false},
{N_("sewage treatment"),  'P',  c_red,    5, no_extras, true, false},
{N_("sewage treatment"),  'P',  c_green,  5, no_extras, false, true},
{N_("sewage treatment"),  'P',  c_green,  5, no_extras, false, false},
{N_("mine entrance"), 'M',  c_ltgray, 5, no_extras, true, false},
{N_("mine shaft"),    'O',  c_dkgray, 5, no_extras, true, true},
{N_("mine"),    'M',  c_brown,  2, no_extras, false, false},
{N_("mine"),    'M',  c_brown,  2, no_extras, false, false},
{N_("mine"),    'M',  c_brown,  2, no_extras, false, false},
{N_("spiral cavern"), '@',  c_pink,   2, no_extras, false, false},
{N_("spiral cavern"), '@',  c_pink,   2, no_extras, false, false},
{N_("radio tower"),         'X',    c_ltgray,       2, no_extras, false, false},
{N_("toxic waste dump"),  'D',  c_pink,   2, no_extras, false, false},
{N_("cave"),    'C',  c_brown,  2, field_extras, false, false},
{N_("rat cave"),    'C',  c_dkgray, 2, no_extras, true, false},
{N_("cavern"),    '0',  c_ltgray, 2, no_extras, false, false},
{N_("anthill"),   '%',  c_brown,  2, no_extras, true, false},
{N_("solid rock"),    '%',  c_dkgray, 5, no_extras, false, false},
{N_("rift"),    '^',  c_red,    2, no_extras, false, false},
{N_("hellmouth"),   '^',  c_ltred,  2, no_extras, true, false},
{N_("slime pit"),   '~',  c_ltgreen,  2, no_extras, true, false},
{N_("slime pit"),   '~',  c_ltgreen,  2, no_extras, false, false},
{N_("triffid grove"), 'T',  c_ltred,  5, no_extras, true, false},
{N_("triffid roots"), 'T',  c_ltred,  5, no_extras, true, true},
{N_("triffid heart"), 'T',  c_red,    5, no_extras, false, true},
{N_("basement"),    'O',  c_dkgray, 5, no_extras, false, true},
{N_("subway station"),  'S',  c_yellow, 5, subway_extras, false, true},
{N_("subway"),        LINE_XOXO,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_OXOX,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_XXOO,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_OXXO,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_OOXX,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_XOOX,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_XXXO,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_XXOX,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_XOXX,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_OXXX,  c_dkgray, 5, subway_extras, false, false},
{N_("subway"),        LINE_XXXX,  c_dkgray, 5, subway_extras, false, false},
{N_("sewer"),         LINE_XOXO,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_OXOX,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_XXOO,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_OXXO,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_OOXX,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_XOOX,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_XXXO,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_XXOX,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_XOXX,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_OXXX,  c_green,  5, no_extras, false, false},
{N_("sewer"),         LINE_XXXX,  c_green,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_XOXO,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_OXOX,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_XXOO,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_OXXO,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_OOXX,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_XOOX,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_XXXO,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_XXOX,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_XOXX,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_OXXX,  c_brown,  5, no_extras, false, false},
{N_("ant tunnel"),    LINE_XXXX,  c_brown,  5, no_extras, false, false},
{N_("ant food storage"),  'O',  c_green,  5, no_extras, false, false},
{N_("ant larva chamber"), 'O',  c_white,  5, no_extras, false, false},
{N_("ant queen chamber"), 'O',  c_red,    5, no_extras, false, false},
{N_("cavern"),    '0',  c_ltgray, 5, no_extras, false, false},
{N_("tutorial room"), 'O',  c_cyan,   5, no_extras, false, false}
};

